# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170503_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelFoo',
        ),
    ]
