# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisher',
            new_name='publisher_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
