# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170511_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
