# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(blank=True, upload_to='featured_images'),
        ),
    ]
