# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('blog', '0014_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
