# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.profile'),
        ),
    ]
