# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170712_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogSettings',
            new_name='Setting',
        ),
    ]
