# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170715_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
